# Generated by Django 4.1.7 on 2023-05-05 00:33

import carreras.choises
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la materia')),
                ('duracion', enumchoicefield.fields.EnumChoiceField(default=carreras.choises.DuracionMateria['SEMESTRAL'], enum_class=carreras.choises.DuracionMateria, max_length=12, verbose_name='Duracion de la materia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'unique_together': {('nombre', 'carrera')},
            },
        ),
    ]
